### ISSUE TITLE
Snippet Form cannot find AJAX Handler 'renderForm::onSubmit'

### ISSUE THREAD

**Issue by sqwk** [mplodowski/formbuilder-plugin-public#36] opened 2023-09-05 19:11 UTC
When using the "Render Form Component" snippet inside a static page (variable, not the content field), the form gets rendered to the page but cannot be submitted. On submit an alert shows up "AJAX Handler 'renderForm::onSubmit' cannot be found" and the POST to the same page produces an error 500.

When using the "Render Form Component" component inside a CMS page, everything works fine.

October v3.4.15

Plugin v3.1.2

**Comment by sqwk** [comment] 2023-09-06 11:12
The problem also occurs when downgrading the plugin to v3.0.0.

**Comment by sqwk** [comment] 2023-09-06 12:43
Changing the `registerPageSnippets()` method inside `Plugin.php` to use an absolute class name seems to fix the problem:

```php
public function registerPageSnippets()
{
    return [
        \Renatio\FormBuilder\Components\RenderForm::class => 'renderForm',
    ];
}
```

**Comment by mplodowski** [comment] 2023-09-06 13:53
Hi,

I checked this and it seems to work find with example Contact Form.

October v3.4.15
Plugin v3.1.2
Pages plugin: v1.5.12

Hmm the most weird thing is that the change you made to make it work does not make any sense. 

If you:

```
dd(
    [\Renatio\FormBuilder\Components\RenderForm::class => 'renderForm'],
    [RenderForm::class => 'renderForm'],
);
```

This is exactly the same, because first one use fully qualified name and the second shortcut with use import.

**Comment by sqwk** [comment] 2023-09-06 14:24
OK, very weird. I undid the qualified name and it still works. So that was a false flag. Sorry, about that.

However, I noticed that when I edit the `componentDetails()`method inside `RenderForm.php` as below, the snippet code that is inserted in a static page changes to include `<figure data-ajax=\"true\" ...` and the snippet starts working.

```php
public function componentDetails()
{
    return [
        'name' => 'renatio.formbuilder::lang.render_form.name',
        'description' => 'renatio.formbuilder::lang.render_form.description',
        'snippetAjax' => true
    ];
}
```

Could it be that the `data-ajax` is needed? (See https://docs.octobercms.com/3.x/cms/themes/snippets.html#creating-snippets-from-components)

**Comment by mplodowski** [comment] 2023-09-07 09:39
Hi,

yes that is probably the issue here. This is a new feature of October, so I did not add it yet. Thanks for reporting this.

I published v3.1.3 where this is added.

Thanks for reporting this and help resolving this.

**Comment by xmerlin** [comment] 2023-10-13 13:52
Same problem here FormBuilder 4.0.2, octobercms 3.5.4 (also 3.5.x)

"AJAX handler 'renderForm::onSubmit' was not found"

**Comment by mplodowski** [comment] 2023-10-13 16:08
Hi @xmerlin,

please write me steps to reproduce this issue.

**Comment by mplodowski** [comment] 2023-10-13 16:17
Please copy your homepage and layout file source code. Just the minimum with the form and essential code.

**Comment by xmerlin** [comment] 2023-10-13 16:20
layout 

`<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700|Poppins:300,400,500,600,700|PT+Serif:400,400i&display=swap" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="{{ [
....
	]|theme }}" type="text/css" />
	{% styles %}

...
</head>

<body class="stretched">


	<div id="wrapper" class="clearfix">
		{% partial "header" %}
		{% page %}
        {% partial "footer" %}
	</div>

	<div id="gotoTop" class="icon-angle-up"></div>

	<script src="{{ [ 
		'assets/js/jquery.js',
		'assets/js/plugins.min.js',
		'assets/js/functions.js'
	]|theme}}"></script>

	{% framework extras %}
	{% scripts %}

</body>
</html>`

concact-form partial

`

<section id="map-overlay">
    <div class="container clearfix">
        <div id="contact-form-overlay" class="clearfix">
            <div class="fancy-title title-dotted-border">
                <h3>Send us an Email</h3>
            </div>

            <div class="contact-widget">
                <div class="contact-form-result"></div>
                {% component "renderForm"%}
            </div>
        </div>
    </div>
</section>

`

**Comment by mplodowski** [comment] 2023-10-13 16:27
I assume that you use partial and put form component inside it.

Maybe this is the isssue: https://talk.octobercms.com/t/ajax-handler-in-php-section-of-partial/1009

https://docs.octobercms.com/3.x/markup/tag/ajax-partial.html

So instead of use {% partial 'contact-form' %} try to use {% ajaxPartial 'contact-form' %}

**Comment by xmerlin** [comment] 2023-10-13 16:32
{% ajaxPartial 'contact-form' %} fixed the issue ...now I have to find why there is no message in the form log and/or in mailbox

**Comment by mplodowski** [comment] 2023-10-13 17:34
I would check mail settings first. Go to Settings -> Mail Templates and click any mail template. There is a Sent test message button below. If you receive test message, then check Event Logs for any errors.

In form update page there is Options tab, where is setting to disable form logs. Check if it is not disabled.

Also to receive mail message the Mail Template field must not be empty.

**Closed** 2023-10-14 12:04 UTC

**Comment by xmerlin** [comment] 2023-10-14 17:05
Mail Template field empty ...now it works as expected, thank you
